// Code generated by mockery v1.0.0
package mocks

import "github.com/stretchr/testify/mock"

// PwdAlgo is an autogenerated mock type for the PwdAlgo type
type PwdAlgo struct {
	mock.Mock
}

// Compare provides a mock function with given fields: hash, password
func (_m *PwdAlgo) Compare(hash string, password string) (bool, error) {
	ret := _m.Called(hash, password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hash, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hash provides a mock function with given fields: p
func (_m *PwdAlgo) Hash(p string) (string, error) {
	ret := _m.Called(p)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
